spring.application.name=LendingApplication
spring.datasource.url=jdbc:mysql://localhost:3306/alendingapplication

#sanjana
spring.datasource.username=admin
spring.datasource.password=SudipRinku@29

#prathmesh
#spring.datasource.username=tripathi
#spring.datasource.password=111803

#parth
#spring.datasource.username=admin
#spring.datasource.password=Amit@14



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=sanjanad845@gmail.com
mail.smtp.password=fwin jcpy tsdb neot
mail.smtp.auth=true
mail.smtp.starttls.enable=true


spring.security.user.name=sanjana
spring.security.user.password=2302

jwt.expiration=604800000
jwt.secret=89d085667175c0271559ca898180eee71a62b8a2ccab448a7e3c09e813758403


cloudinary.cloud-name=dmduj1e9w
cloudinary.api-key=528197738973168
cloudinary.api-secret=hZOnCK-bYDobACGLgPUINtBAAMY

razorpay.key.id=rzp_test_WQHkBDkVolcpQE
razorpay.key.secret=DNlDP6kWVXcEX3r7HvvVQQBl
